/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dangnhapcuoiky;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class DangKy extends javax.swing.JFrame {

    /**
     * Creates new form DangKy
     */
    public DangKy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_hoTen = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jLabel_fb = new javax.swing.JLabel();
        jLabel_sdt = new javax.swing.JLabel();
        jLabel_pw = new javax.swing.JLabel();
        jLabel_pwa = new javax.swing.JLabel();
        jTextField_PWA = new javax.swing.JTextField();
        jTextField_PW = new javax.swing.JTextField();
        jTextField_FB = new javax.swing.JTextField();
        jTextField_SDT = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jTextField_Ten = new javax.swing.JTextField();
        jButton_DK = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton_DN = new javax.swing.JButton();
        jLabel_TBTEN = new javax.swing.JLabel();
        jLabel_TBEmail = new javax.swing.JLabel();
        jLabel_TBSDT = new javax.swing.JLabel();
        jLabel_TBFB = new javax.swing.JLabel();
        jLabel_TBPW = new javax.swing.JLabel();
        jLabel_PWA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_hoTen.setText("Họ Tên:");

        jLabel_email.setText("Email:");

        jLabel_fb.setText("Facebook:");

        jLabel_sdt.setText("SDT:");

        jLabel_pw.setText("Password:");

        jLabel_pwa.setText("nhập lại password:");

        jTextField_Ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TenActionPerformed(evt);
            }
        });

        jButton_DK.setText("OK");
        jButton_DK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DKActionPerformed(evt);
            }
        });

        jLabel8.setText("Đăng Ký");

        jButton_DN.setText("Dăng Nhập");
        jButton_DN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_DN)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton_DK))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_pwa)
                            .addComponent(jLabel_sdt)
                            .addComponent(jLabel_email)
                            .addComponent(jLabel_hoTen)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel_fb))
                            .addComponent(jLabel_pw))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_PWA, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(jTextField_Email)
                            .addComponent(jTextField_SDT)
                            .addComponent(jTextField_Ten)
                            .addComponent(jTextField_FB)
                            .addComponent(jLabel_TBTEN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_TBEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_TBSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_PW, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_TBFB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_TBPW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_PWA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_hoTen)
                    .addComponent(jTextField_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_TBTEN, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_email)
                    .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_TBEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_sdt)
                    .addComponent(jTextField_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_TBSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_FB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_fb, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_TBFB, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_PW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_pw))
                .addGap(4, 4, 4)
                .addComponent(jLabel_TBPW, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_pwa)
                    .addComponent(jTextField_PWA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_PWA, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton_DK)
                .addGap(18, 18, 18)
                .addComponent(jButton_DN)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_DKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DKActionPerformed
        // TODO add your handling code here:
        DanhSach ds= new DanhSach();
        int ten=0,email=0,sdt=0,fb=0,pw=0,pwa=0;
        
        if(jTextField_Ten.getText().isEmpty()){
            jLabel_TBTEN.setText("Ten khong duoc de trong");
        }
        else{
            ten=1;
            jLabel_TBTEN.setText("");
        }
        if(jTextField_Email.getText().isEmpty()){
            jLabel_TBEmail.setText("Email ko dc de trong");
        }
        else if(ds.checkEmail(jTextField_Email.getText())==false){
            email=0;
            jLabel_TBEmail.setText("Email bi trung");
        }
        else{
            email=1;
            jLabel_TBEmail.setText("");
        }
        if(jTextField_FB.getText().isEmpty()){
            jLabel_TBFB.setText("FB ko duoc de trong");
        }
        else if(ds.checkFB(jTextField_FB.getText())==false){
            fb=0;
            jLabel_TBFB.setText("fb bi trung");
        }
        else{
            fb=1;
            jLabel_TBFB.setText("");
        }
        if(jTextField_PW.getText().isEmpty()){
            jLabel_TBPW.setText("password ko duoc de trong");
        }
        else{
            pw=1;
            jLabel_TBPW.setText("");
        }
        if(jTextField_PWA.getText().isEmpty()){
            jLabel_PWA.setText("ko duoc de trong");
        }
        else{
            pwa=1;
            jLabel_PWA.setText("");
        }
        if(jTextField_SDT.getText().isEmpty()){
            jLabel_TBSDT.setText("sdt ko duoc de trong");
        }else if(ds.checkSDT(jTextField_SDT.getText()) == false){
            fb=0;
            jLabel_TBSDT.setText("sdt bi trung");
        }

        else{
            sdt=1;
            jLabel_TBSDT.setText("");
        }
        if(jTextField_PW.getText().equals(jTextField_PWA.getText())==false){
            pwa=0;
            jLabel_PWA.setText("ko trung voi password");
        }
        else{
            pwa=1;
            jLabel_PWA.setText("");
        }
        if(email==1&&ten==1&&fb==1&&fb==1&&pw==1&&pwa==1&&sdt==1){
            ds.LuuThongTin(jTextField_Ten.getText(), jTextField_SDT.getText(), jTextField_Email.getText(), jTextField_FB.getText(), jTextField_PW.getText());
            JOptionPane.showMessageDialog(this,"Đăng Ký Thành Công");
        }
    }//GEN-LAST:event_jButton_DKActionPerformed

    private void jButton_DNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DangNhap().setVisible(true);
    }//GEN-LAST:event_jButton_DNActionPerformed

    private void jTextField_TenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_DK;
    private javax.swing.JButton jButton_DN;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_PWA;
    private javax.swing.JLabel jLabel_TBEmail;
    private javax.swing.JLabel jLabel_TBFB;
    private javax.swing.JLabel jLabel_TBPW;
    private javax.swing.JLabel jLabel_TBSDT;
    private javax.swing.JLabel jLabel_TBTEN;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_fb;
    private javax.swing.JLabel jLabel_hoTen;
    private javax.swing.JLabel jLabel_pw;
    private javax.swing.JLabel jLabel_pwa;
    private javax.swing.JLabel jLabel_sdt;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_FB;
    private javax.swing.JTextField jTextField_PW;
    private javax.swing.JTextField jTextField_PWA;
    private javax.swing.JTextField jTextField_SDT;
    private javax.swing.JTextField jTextField_Ten;
    // End of variables declaration//GEN-END:variables
}
